version: 1
formatters:
  simple:
    format: '%(asctime)s.%(msecs)03d-[%(levelname)s]%(message)s'
    datefmt: '%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  main_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/main.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 240240000
    encoding: utf8
  communicator_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/communicator.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 240240000
    encoding: utf8  
loggers:
  sampleLogger:
    level: DEBUG
    handlers: []
    propagate: no
  mainLogger:
    level: DEBUG
    handlers: [main_file_handler]
    propagate: no
  communicatorLogger:
    level: DEBUG
    handlers: [communicator_file_handler]
    propagate: no
root: